# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '* */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: test

    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.test }}
