name: GitHub-Profile-Summary-Cards

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - name: Get current date
        id: date
        run: date +'%Y-%m-%d'
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          UTC_OFFSET: 8
          EXCLUDE: "java"
          AUTO_PUSH: true
